### ISSUE TITLE
person & org info from DBPedias, WD, DNB, KB, permid

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/databus-content#1]
https://wiki.dbpedia.org/blog/dbpedia-databus-%E2%80%93-transforming-linked-data-networked-data-economy shows this image:
![](https://blog.dbpedia.org/wp-content/uploads/2018/05/2018-05-15-16-54-docs.google.com_.png)

Showing person & org info from DBPedias, WD, DNB, KB, permid.
- Where can I find it? https://databus.dbpedia.org search for "permid" doesn't find anything
- Are the entities matched across datasets?

Thanks! cc @kurzum

**Comment by kurzum** [comment]
@VladimirAlexiev can you repost this in https://forum.dbpedia.org

**Comment by VladimirAlexiev** [comment]
https://forum.dbpedia.org/t/person-org-info-from-dbp-wd-dnb-kb-permid/108
