### ISSUE TITLE
broken links under /system

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/databus-content#2]
https://databus.dbpedia.org search for "timbr" shows a bsystem description. But clicking on each of the breadcrumbs results in broken link:
- https://databus.dbpedia.org/system/
- https://databus.dbpedia.org/system/service/
- https://databus.dbpedia.org/system/service/timbr/
- https://databus.dbpedia.org/system/service/timbr/timbr-dbpedia/

**Comment by kurzum** [comment]
moved here: https://github.com/dbpedia/databus-maven-plugin/issues/81

**Comment by kurzum** [comment]
we use the `website` tag, in this repo there is only the metadata loaded into the store.
