### ISSUE TITLE
blog broken link

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/databus-content#3]
The blog https://wiki.dbpedia.org/blog/dbpedia-databus-%E2%80%93-transforming-linked-data-networked-data-economy is pretty important because it's linked form the databus home page.

This link in it is broken:
Load all data in the comparison tool: http://88.99.242.78:9000/?s=http%3A%2F%2Fid.dbpedia.org%2Fglobal%2F12HpzV&p=http%3A%2F%2Fdbpedia.org%2Fontology%2Farchitect&src=general

**Comment by kurzum** [comment]
I updated the link in the blog post, thanks:

> Load all data in the comparison tool: 
Update 21/08/2019: The comparison tool developed into a data browser hosted at https://global.dbpedia.org , source code
